# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    #types: [opened, synchronize, closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_windows:

    name: Build (OS Windows)

    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out current repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          token: ${{ github.token }}

      - name: Install Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      # Runs a single command using the cmd
      - name: Build graph
        shell: cmd
        env:
          target_file_path: ${{github.workspace}}${{'\\scripts\\compile.bat'}}
        run: |
          @REM @ECHO OFF
          ECHO Target file: "%target_file_path%".
          ECHO ----------------------------------------
          CALL "%target_file_path%"

  ci_job_cancel_test:
    name: CI job cancel test
    #runs-on: windows-latest
    steps:
      - name: Job cancel
        run: SIGINT
