# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_windows:

    name: Build (OS Windows)

    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: ts-graphviz/setup-graphviz@v1
      - name: Check out (clone) my current repo
        uses: actions/checkout@master
        with:
          repository: ${{ github.repository }}     # <-- clone https://github.com/Gesugao-san/SS13-Codebases
          #token: ${{ secrets.my_pat }}
        #run: git clone ${{ github.repository }}

      # Runs a single command using the cmd
      - name: Build graph
        shell: cmd
        run: |
          @REM @ECHO OFF
          ECHO Current dir: %CD%\
          DIR
          CD ..
          DIR
          CD ..
          DIR
          CD ..
          DIR
          ECHO Project dir: %CD%\
          ECHO Target file: "%CD%\\scripts\\compile.bat"

          REM ECHO ----------------------------------------
          REM ECHO 1: CDs...
          REM "%CD%/scripts/compile.bat"   & @REM The system cannot find the path specified.
          REM "%CD%\\scripts\\compile.bat" & @REM The system cannot find the path specified.
          REM "%CD%\scripts\compile.bat"   & @REM The system cannot find the path specified.
